version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: inventory-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://inventory_user:inventory_password@postgres:5432/inventory_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - inventory-network
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:

networks:
  inventory-network:
    driver: bridge
