services:
  - type: web
    name: inventory-management-api
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISABLE_AUTH
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: SHADOW_DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: "https://inventory-application-d4u1.onrender.com,http://localhost:5173,http://localhost:3000"

