services:
  - type: web
    name: inventory-management-api
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISABLE_AUTH
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: SHADOW_DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:5173

